project_id = "vwmopjkrnjrxkbxsswnb"

[functions.google-maps-proxy]
verify_jwt = false

[functions.weather-service]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.activate-trial]
verify_jwt = true

[functions.mapbox-token]
verify_jwt = false

[functions.update-charging-stations]
verify_jwt = false